### ISSUE TITLE
code  on nuScenes

### ISSUE THREAD

**Issue by Alreall** [mengmengliu1998/GATraj#2]
Hi, @mengmengliu1998 I have had the pleasure of reading your paper, I feel it is very well written, now I want to study the code of the paper, I see you have provided the code on ETH/UCY dataset, I would like to ask if you are convenient to provide the code on nuScenes dataset, if it is convenient can you send it to my email,  lizhao128023@163.com,

**Comment by mengmengliu1998** [comment]
For nuScenes data preprocessing, you can follow the Agentformer [Agentformer](https://github.com/Khrylx/AgentFormer)
