### ISSUE TITLE
nuScene dataset

### ISSUE THREAD

**Issue by chenxi-xr** [mengmengliu1998/GATraj#3]
Hello, I have recently read your article and your proposed framework is excellent. I would like to further understand how the model is applied to the nuScene dataset? I would like to ask if you are convenient to provide the code on nuScenes dataset. Thank you！ This is my email: xr2970395545@163.com

**Comment by zehranrgi** [comment]
Hey, is there any update? which dataset did you use from nuscene?  @chenxi-xr @haohao11 @mengmengliu1998

**Comment by mengmengliu1998** [comment]
For nuScenes data preprocessing, you can follow the Agentformer [Agentformer](https://github.com/Khrylx/AgentFormer)

**Comment by MaartenHugenholtz** [comment]
Hello, did someone train the model on NuScenes, who could share the model weights?
Thank you!
